name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker Action
      uses: jerray/publish-docker-action@v1.0.3
      with:
        # Username used to login docker registry
        username: ${{ secrets.dockerHubUsername }}
        # Password used to login docker registry
        password: ${{ secrets.dockerHubSecret }}
        # Docker build context
        path: source/TestAuthorityCore
        file: source/TestAuthorityCore/Dockerfile
        repository: nomail/test-authority
        tag_with_ref: true
