name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Publish Docker Action
      uses: jerray/publish-docker-action@v1.0.3
      with:
      # Username used to login docker registry
        username: ${{ secrets.dockerHubUsername }}
        # Password used to login docker registry
        password: ${{ secrets.dockerHubSecret }}
        # Docker build context
        path: source/TestAuthorityCore       
